[package]
name = "commbox-cli"
version = "0.1.0"
edition = "2024"
license = "MIT"

[dependencies]
tokio = { version = "1", features = ["rt-multi-thread", "macros", "net", "io-util", "time"] }
anyhow = "1"
clap = { version = "4", features = ["derive"] }
futures = "0.3"
inquire = "0.7"
indicatif = "0.17"